name: "Deploy-Environment"

on:
  # This is a reusable workflow
  workflow_call:
    inputs: 
      environment:
        description: "Name of the environment to deploy"
        required: true
        type: string
      pr_head_ref:
        description: "Working branch of Pull Request"
        required: true
        type: string
      pr_base_ref:
        description: "Working branch of Pull Request"
        required: true
        type: string
        
jobs:
  build-code:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{inputs.pr_base_ref}}
          
      - name: Print information
        run: |
          echo "Environment:${{inputs.environment}}"
          echo "PR Branch:${{inputs.pr_head_ref}}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          json: true
          sha: ${{inputs.pr_head_ref}} 

      - name: List all changed files
        shell: pwsh
        env:
          ALL_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_modified_files }}
        run: |
          write-host $Env:ALL_MODIFIED_FILES

      # - name: Merge ${{inputs.pr_head_ref}} branch to 'Release'
      #   run: |
      #     git checkout ${{inputs.pr_base_ref}}
      #     git merge ${{inputs.pr_head_ref}}
      #     git push
