name: "Deploy-Environment"

on:
  # This is a reusable workflow
  workflow_call:
    inputs: 
      environment:
        description: "Name of the environment to deploy"
        required: true
        type: string
      pr_head_ref:
        description: "Working branch of Pull Request"
        required: true
        type: string

# permissions:
#   id-token: write
#   contents: read

# defaults:
#   run:
#     shell: pwsh

jobs:
  build-code:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Getting Branch
        run: |
          echo "Environment:${{inputs.environment}}"
          echo "PR Branch:${{inputs.pr_head_ref}}"
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
