# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  resolve:
    name: "Resolve environment"
    uses: ./.github/workflows/resolve-environment.yml
    with:
      pr_head_ref: "${{github.head_ref}}"
      pr_base_ref: "master"
      environment: QA
      
  prod-approval-gate:
    name: "Approve content push to: ${{needs.resolve.outputs.resolved_environment}}"
    needs: resolve
    environment: ${{needs.resolve.outputs.resolved_environment}}
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env: 
          ENV_NAME: ${{needs.resolve.outputs.resolved_environment}}
        run: echo "Approve for %ENV_NAME%"
    
  prod-deploy:
    name: "Push content to ${{needs.resolve.outputs.resolved_environment}}"
    needs: prod-approval-gate
    uses: ./.github/workflows/merge-prod.yml
    with:
      pr_head_ref: "${{github.head_ref}}"
      pr_base_ref: "Release"
      environment: ${{needs.resolve.outputs.resolved_environment}}
