# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  qa-deploy:
    uses: ./.github/workflows/deploy-environment-qa.yml
    with:
      pr_head_ref: "${{github.head_ref}}"
      pr_base_ref: "master"
      environment: QA
      
  prod-approval-gate:
    needs: qa-deploy
    environment: ${{needs.qa-deploy.outputs.resolved_environment}}
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env: 
          ENV_NAME: ${{needs.qa-deploy.outputs.resolved_environment}}
        run: echo "Approve for $($env.ENV_NAME)"
    
  prod-deploy:
    needs: prod-approval-gate
    uses: ./.github/workflows/deploy-environment-prod.yml
    with:
      pr_head_ref: "${{github.head_ref}}"
      pr_base_ref: "Release"
      environment: ${{needs.qa-deploy.outputs.resolved_environment}}
